repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1  # Update me!
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/psf/black
    rev: 21.9b0  # Update me!
    hooks:
    - id: black

-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.2  # Update me!
    hooks:
    -   id: flake8

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.0  # Update me!
    hooks:
    - id: bandit

-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.2.2  # Update me!
    hooks:
    -   id: python-safety-dependencies-check
